/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercise9;

/**
 *
 * @author suhrda01
 */
public class Ex9ConverterGUI extends javax.swing.JFrame {

    /**
     * Creates new form Ex9ConverterGUI
     */
    public Ex9ConverterGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldTempFrom = new javax.swing.JTextField();
        jButtonConvert = new javax.swing.JButton();
        jTextFieldTempTo = new javax.swing.JTextField();
        jComboBoxUnitFrom = new javax.swing.JComboBox<>();
        jComboBoxUnitTo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConvert.setText("Convert");
        jButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertActionPerformed(evt);
            }
        });

        jTextFieldTempTo.setEditable(false);

        jComboBoxUnitFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelvin", "Farenheit", "Celsius" }));
        jComboBoxUnitFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnitFromActionPerformed(evt);
            }
        });

        jComboBoxUnitTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelvin", "Celsius", "Farenheit" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonConvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextFieldTempTo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxUnitTo, 0, 94, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextFieldTempFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxUnitFrom, 0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTempFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUnitFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConvert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTempTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUnitTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxUnitFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnitFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUnitFromActionPerformed

    private void jButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertActionPerformed
        double tempFrom = Double.parseDouble(jTextFieldTempFrom.getText());
        String unitFrom = (String) jComboBoxUnitFrom.getSelectedItem();
        String unitTo = (String) jComboBoxUnitTo.getSelectedItem();
        Ex9Converter converter = new Ex9Converter();
        if ("Farenheit".equals(unitFrom)) {
           if ("Celsius".equals(unitTo)) {
               jTextFieldTempTo.setText(Double.toString(converter.f2c(tempFrom)));
           } else if ("Farenheit".equals(unitTo)){
               jTextFieldTempTo.setText(Double.toString(tempFrom));
           } else {
               jTextFieldTempTo.setText(Double.toString(converter.f2k(tempFrom)));
           }
        } else if ("Celsius".equals(unitFrom)) {
           if ("Celsius".equals(unitTo)){
               jTextFieldTempTo.setText(Double.toString(tempFrom));
           } else if ("Farenheit".equals(unitTo)) {
               jTextFieldTempTo.setText(Double.toString(converter.c2f(tempFrom)));
           } else {
               jTextFieldTempTo.setText(Double.toString(converter.c2k(tempFrom)));
           }
        } else {
           if ("Celsius".equals(unitTo)) {
               jTextFieldTempTo.setText(Double.toString(converter.k2c(tempFrom)));
           } else if ("Farenheit".equals(unitTo)){
               jTextFieldTempTo.setText(Double.toString(converter.k2f(tempFrom)));
           } else {
               jTextFieldTempTo.setText(Double.toString(tempFrom));
           }
        }
    }//GEN-LAST:event_jButtonConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ex9ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ex9ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ex9ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ex9ConverterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ex9ConverterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvert;
    private javax.swing.JComboBox<String> jComboBoxUnitFrom;
    private javax.swing.JComboBox<String> jComboBoxUnitTo;
    private javax.swing.JTextField jTextFieldTempFrom;
    private javax.swing.JTextField jTextFieldTempTo;
    // End of variables declaration//GEN-END:variables
}
